### ISSUE TITLE
Anonymous with parent type and interface

### ISSUE THREAD

**Issue by edvineshagh** [dotlattice/LatticeUtils#3]
Hi,
I have a use-case that requires the anonymous type to be a subclass and implement an interface.
I forked your repository and simply passed a parent type and an interface array into moduleBuilder.DefineType (...).
The update works great; and I even added a unit test for verification; however, the unit test fails when I "Run All" tests (works by itself).  I'm wondering if you have any thoughts why this might be an issue.  If I/we can figure it out, I can issue a pull request back.

You can see the forked project here: https://github.com/edvineshagh/LatticeUtils

Tnx,
Edvin

**Comment by edvineshagh** [comment]
Upon further investigation, I find that the issue is related to multiple properties, which you addressed in first reported defect (https://github.com/dotlattice/LatticeUtils/issues/1) under version 2.0.0.3; however, the latest version on Github is 2.0.0.  Also, I see that the Nuget package has version 2.0.0.4.
Can you update the source code on Github so that I can work against the latest build...

Tnx,
Edvin

**Comment by dotlattice** [comment]
Hi, thanks for the feedback!  Being able to create an anonymous type that extends a class or implements some interfaces does seem useful, so I'd be up for adding that feature.  I'll try the code out on your fork and see if I can figure out what the issue is.

The code on github should be the latest version, and it looks like the fix for #1 was in your fork.  But it looks like I haven't published a compiled release on github yet with the last couple fixes.  I'll push one of those out after this issue is completed.

As for the other broken unit test, I'm seeing that on the current version of the code, too.  It looks like one of the tests is making assumptions about how the GetHashCode() method is implemented for real anonymous types, and that must have changed in the new Roslyn compiler for C# 6.  So I'll get that test fixed, too.

**Comment by edvineshagh** [comment]
Tnx for the contribution.  It is a useful utility when we need to workaround strongly type classes.

**Comment by dotlattice** [comment]
Good news!  I made some changes in the latest release to support a parent class for anonymous types.  And I put out a new release on github and in NuGet with the changes.

It looks like the reason you were seeing your tests fail when you run all is because the anonymous type name wasn't updated to include the parent class information.  So if another test ran first with the same property names, then the type is already created without a parent class and you will get that type back when your test runs.

I refactored the way the type name is generated to make it easier to add additional options.  So now it includes the property names and parent class, and it should be easier to add additional information there if needed in the future.

One other note: the current release does not include support for adding interfaces to an anonymous type.  While it would be easy to support empty interfaces or interfaces that just have properties, it would get a lot harder to provide more general interface support (you'd need a way to provide an implementation for methods, the utility would probably need to check that you're actually adding all properties that the interface requires, etc.).

If that is something you need, then feel free to open another ticket for interface support.  I wouldn't rule out adding it, but it probably wouldn't be a high priority unless there's a really good use case for it.

**Comment by edvineshagh** [comment]
That is awsome.
I agree with your assessment in regards to interfaces...
Thanks again.
